### ISSUE TITLE
Home button missing

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#100]
## 💁‍♀️ Summary

The icon/text/image/webfont/dingbat for the "home" button is missing. But it is clickable, so _something_ is there! 😉

## 📜 Reproduction

To reproduce as of `Mon Aug 17 22:49:43 UTC 2020`, do the following:

1. Start your favorite web browser.
2. Visit https://edrn-labcas.jpl.nasa.gov/
3. Log in following the prompts.
4. You should now be viewing "LABCAS Collections".
5. In the upper-left corner of the San Marino Blue sidebar, click in the blank area.

## 🖥 Context

This seems to occur on https://mcl-labcas.jpl.nasa.gov/ as well.

## 🖼 Screenshot

<img width="524" alt="Screen Shot 2020-08-17 at 5 46 50 PM" src="https://user-images.githubusercontent.com/814813/90452098-0112d280-e0b3-11ea-9582-0ddcd0bf5686.png">

**Comment by yuliujpl** [comment]
Added.
