### ISSUE TITLE
Skip instructions on Disabling Pop-Ups for Single File Downloads (enhancement, low priority)

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#101]
## 🤔 Tell Us About the Feature

If you check the box by a single file in a dataset, then click the "Download" button, it prompts you to disable blocking of popup windows. It would be nice if it could treat it if a single file is checked as if you pressed the download button. See the screenshot:

![Screen Shot 2020-08-18 at 4 56 25 PM](https://user-images.githubusercontent.com/814813/90569768-0edc5c80-e174-11ea-9548-4643a11508f1.png)

## 🎇 What Solution You'd Like

Pressing the "Download" button with only one file checked should avoid activating the multi-file download facility.

## 〽️ Alternative Ideas

Possibly we may want to do it anyway, to train people to have popups enabled for LabCAS. In this case, pressing the ⬇️ button on the right should also generate the popup warning. What do you think? 🤷‍♀️

## 🗺 Context

This applies to both `edrn-labcas.jpl.nasa.gov` and `mcl-labcas.jpl.nasa.gov`.

**Comment by yuliujpl** [comment]
Resolved!
