### ISSUE TITLE
Remove timestamp from informational alerts

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#103]
## 🤔 Tell Us About the Feature

While using LabCAS 2.0 UI, an alert dialog appeared that included the timestamp `14:13:33`.

This time, in Coordinated Universal Time or Greenwich Mean Time, will be largely useless to the majority of our users. And even if it were in a local time, it still doesn't provide any helpful additional information.

![Screen Shot 2020-09-01 at 9 13 54 AM](https://user-images.githubusercontent.com/814813/91862691-ea808580-ec33-11ea-8d6a-f4ff5978344d.png)

## 🎇 What Solution You'd Like

Drop the timestamp.

In addition, you can make the alert more user friendly with some re-wording, such as: "You are currently logged out. Redirecting you to log in." 🤗

## 🗺 Context

My local time is 9:13:33, and the server's time was 7:13:33.

**Comment by yuliujpl** [comment]
Done
