### ISSUE TITLE
No release tags or branches?

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#105]
LabCAS 2.0 was released in May 2020. LabCAS 2.1 was in September 2020. But there are no release tags in GitHub to reflect this. Releases should be tagged and/or branched so developers can address regressions while development continues on main/master.

**Comment by LucaCinquini** [comment]
I agree but shouldn't this be assigned to David?

**Comment by nutjob4life** [comment]
You are right! @yuliujpl, this is assigned to you.

**Comment by yuliujpl** [comment]
Done, releases created! Branch with release candidate created to help with merging.

**Comment by nutjob4life** [comment]
Re-opening: [GitHub reports](https://github.com/EDRN/labcas-ui/branches/all) that there are no app-specific branches for the LabCAS UI. 

- On edrn-labcas, it seems the LabCAS UI is set to `git@github.com:Labcas-NIST/Labcas-ui.git` — why NIST?  Also: if I do `git status` in `/home/edrn/labcas-ui` I see 31 modified files _not_ in CM and 5 items not checked in at all (`assets/documentation/ohif_dcm_template.json`, ml/`, oh/`, ohif/`, sw.js`) — does these belong in CM?
- On mcl-labcas, the UI is also set to `git@github.com:Labcas-NIST/Labcas-ui.git` — again, is NIST the "bleeding edge"? I see 30 modified files

For deployments-specific branches I would hope to [see them listed here](https://github.com/EDRN/labcas-ui/branches/all) but I'm not seeing them in CM. If this is my overlooking, please let me know 😄

**Comment by nutjob4life** [comment]
@yuliujpl, expanding on [this comment](https://github.com/EDRN/labcas-ui/issues/105#issuecomment-3826183074) I don't see the specific branches for edrn-labcas and mcl-labcas. When I visit https://github.com/EDRN/labcas-ui/branches/all I get this (screenshot):

<img width="342" height="503" alt="branches" src="https://github.com/user-attachments/assets/8c204058-43a3-44dd-b720-aa9c6aec929f" />

Which branch is edrn-labcas, which is mcl-labcas, and which is labcas-dev?

UPDATE: Okay I looked closer and I see that the remote origin URLs for edrn-labcas and mcl-labcas are in [Labcas-NIST](https://github.com/Labcas-NIST), not **here**. (And apparently I [figured that out earlier in this comment](https://github.com/EDRN/labcas-ui/issues/105#issuecomment-3826183074) and totally forgot! 🤪)

So my questions now is:

❓  What's the point of **this** repository?

Is it just for issue tracking? If so, we should move the open issues here to the "new home of the UI" [over here in Labcas-NIST](https://github.com/Labcas-NIST/Labcas-ui)—although it feels weird to have the official home of LabCAS UI be tied to NIST and not a [generic organization](https://github.com/jpl-labcas/).

Second:

❓  Why are edrn-labcas and mcl-labcas out of date?

Assuming we deploy from GitHub (which we probably should be doing), then when I run `git status` I should get "Your branch is up to date".

Instead I see on edrn-labcas:
```
On branch edrn
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   a/faq.html
	modified:   a/index.html
	modified:   assets/js/labcas/authentication.js
	modified:   assets/js/labcas/collections.js
	modified:   assets/js/labcas/dashboard.js
	modified:   assets/js/labcas/dashboard_search.js
	modified:   assets/js/labcas/datasets.js
	modified:   assets/js/labcas/hierarchy_filter_utils.js
	modified:   assets/js/labcas/login.js
	modified:   assets/js/labcas/ml_wizard.js
	modified:   assets/js/labcas/search.js
	modified:   assets/js/labcas/utils.js
	modified:   c/index.html
	modified:   cd/index.html
	deleted:    change_labcas_version.sh
	modified:   d/index.html
	modified:   download.html
	modified:   dwv/index.html
	modified:   f/index.html
	modified:   i/index.html
	modified:   i/mindex.html
	modified:   i/ohif.html
	modified:   index.html
	modified:   m/index.html
	modified:   o/index.html
	modified:   p/index.html
	modified:   pdf/index.html
	modified:   s/index.html
	modified:   sidebar_edrn.html
	modified:   templates.html
	modified:   x/index.html
	modified:   z/index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	assets/documentation/ohif_dcm_template.json
	ml/
	oh/
	ohif/
	sw.js
```
and on mcl-labcas:
```
On branch mcl
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   a/anchor-and-index-date-rules.html
	modified:   a/faq.html
	modified:   a/index.html
	modified:   a/labcas-file-naming-conventions.html
	modified:   a/mcl-cdes.html
	modified:   a/mcl-identifiers.html
	modified:   a/mcl-site-and-investigator-ids.html
	modified:   a/pca-project.html
	modified:   a/sample-data-and-metadata-files.html
	modified:   assets/js/labcas/collections.js
	modified:   assets/js/labcas/dashboard.js
	modified:   assets/js/labcas/dashboard_search.js
	modified:   assets/js/labcas/datasets.js
	modified:   assets/js/labcas/login.js
	modified:   assets/js/labcas/utils.js
	modified:   c/index.html
	modified:   cd/index.html
	modified:   change_labcas_version.sh
	modified:   d/index.html
	modified:   download.html
	modified:   dwv/index.html
	modified:   f/index.html
	modified:   i/index.html
	modified:   i/mindex.html
	modified:   i/ohif.html
	modified:   index.html
	modified:   m/index.html
	modified:   o/index.html
	modified:   p/index.html
	modified:   s/index.html
	modified:   x/index.html
	modified:   z/index.html
```
and on labcas-dev, it's not `Labcas-NIST` nor `jpl-labcas` nor `EDRN`, but a personal, private repository:

    git@github.com:yuliujpl/labcas-dev-private.git
