### ISSUE TITLE
Link to open source image viewers

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#108]
## 🤔 Tell Us About the Feature

Replace this with a clear and concise description of the problem you're tying to solve; for example: I'm frustrated when … or I wish it were easier to …

## 🎇 What Solution You'd Like

Here, put a clear and concise description of what you want to happen.

## 〽️ Alternative Ideas

If you'd like, put in a description of any alternative solutions or features you've considered.

**Comment by yuliujpl** [comment]
Linked
