### ISSUE TITLE
Not all data is showing in a Collection

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#112]
Hi @yuliujpl,
When doing QC on data in LabCAS I ran across a collection (Reproducibility_of_miRNA_Measurements), that looks like it should have more than one page of data files, but when i click on the next page number or > it just gives me a blank page. Maybe there aren't any additional files, but it seems odd that it would show more pages.

https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Reproducibility_of_miRNA_Measurements – shows multiple pages of data, but when clicking to go to the next page it just shows blank.

**Comment by yuliujpl** [comment]
Fixed!
