### ISSUE TITLE
Link to Clinical Viewer

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#113]
Hi @yuliujpl 
Create link in LabCAS UI to clinical viewer similar to links to open an image using a viewer.
For example,
If you are viewing the UVM Clinical data you have a button to open that data using the clinical/biospecimen UI. If you are viewing a participantID metadata you can open the clinical/biospecimen ui. 
Does that make sense? Is that too difficult?
Thanks,
Heather

**Comment by yuliujpl** [comment]
@LucaCinquini @hoodriverheather @asitang  I looked at the mcl-labcas data in solr and could not find any identifiers I can use to link back to clinical-ui. I was wondering if there is a particular dataset you can point out in PCA-Pilot collection that contains an attribute such as participant ID? If I have that, I can easily link it back to clinical-ui.

**Comment by LucaCinquini** [comment]
You are probably right - I think @asitang might need to publish a new dataset with the patient id.

**Comment by hoodriverheather** [comment]
@LucaCinquini @yuliujpl @asitang Yes. We need both ParticipantID and SpecimenID published with every dataset.

**Comment by yuliujpl** [comment]
Tested and working.
