### ISSUE TITLE
Show data custodian and data custodian email at Collection Level

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#114]
Hi @yuliujpl 
Can you make data custodian and data custodian email visible at the dataset level? 
Thanks,
Heather

**Comment by yuliujpl** [comment]
@LucaCinquini @asitang fyi! I sometimes see "data custodian" and sometimes see "datacustodian"

https://edrn-labcas.jpl.nasa.gov/data-access-api/datasets/select?q=DatasetParentId%22Canary_Never-smoker_lung_adenocarcinoma/DNA_METHYLATION_LEV2%22%5C%2A&wt=json&indent=true&rows=10000&sort=id%20asc

https://mcl-labcas.jpl.nasa.gov/data-access-api/datasets/select?q=id:%22PCA_Pilot_Data/Smart_3Seq_RNA_Sequencing/University_of_Vermont_Smart3Seq_Data%22&wt=json&indent=true

**Comment by yuliujpl** [comment]
@hoodriverheather done for MCL, believe this was previously enabled for edrn!

**Comment by hoodriverheather** [comment]
@yuliujpl @asitang @LucaCinquini Is this something I should fix in the metadata?
