### ISSUE TITLE
Add Abbreviated Protocol Name to LabCAS metadata

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#117]
## 🤔 Tell Us About the Feature

Is it possible to add the abbreviated or short protocol title to the metadata for EDRN LabCAS data and populate field based on the protocol id?

For example:
Prostate MRI collection in LabCAS - https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Prostate_MRI is linked to Protocol 430. 

https://edrn.nci.nih.gov/data-and-resources/protocols/430-prostate-mri

Add metadata field - Abbreviated Name: and populate with value "P-MRI".

**Comment by yuliujpl** [comment]
Hi @hoodriverheather ! For some reason, I can't seem to find a entry in KSDB that's similar to prostate MRI with an ID 430. Is this already entered into KSDB or still need to be entered there? Thanks!

**Comment by hoodriverheather** [comment]
@yuliujpl These are EDRN protocols that come from the DMCC via SOAP API. They are in the Portal. Can they be automatically populated?

**Comment by yuliujpl** [comment]
@hoodriverheather  Got it! I may need to ingest into KSDB first before querying it from labcas. There's only so many systems that can talk to each other so limiting it to KSDB as the central source of metadata will help ensure labcas-ui's will only have one or two endpoint(s) to ingest data. Thanks!

**Comment by hoodriverheather** [comment]
@yuliujpl Sounds good. Maybe we should meet w Sean to discuss best way to handle this.

**Comment by yuliujpl** [comment]
Done
