### ISSUE TITLE
Security Vulnerability: embeddable JavaScript in URL

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#119]
## 🐛 Describe the Bug

It's possible to embed JavaScript in a URL and have it executed by the browser, presenting a cross-site scripting vulnerability. Using a crafted URL, the LabCAS UI does not sanitize its input and makes the user's browser execute the code.

## 📜 How To Reproduce

For this example, we will use the following specially crafted URL:

    https://mcl-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=VUMC_Lung_Adenocarcinoma_CyTOF_data%3Cscript%3Ealert%28269%29%3C%2Fscript%3E

Note that this URL has a JavaScript `alert` box encoded within it.

1. Visit https://mcl-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=VUMC_Lung_Adenocarcinoma_CyTOF_data%3Cscript%3Ealert%28269%29%3C%2Fscript%3E
2. Notice that the user's browser shows the alert.

## 🔎 Expected Behavior

The LabCAS UI must sanitize its input parameters to prevent code like this from executing.

## 🖼 Screenshots

<img width="1156" alt="Screen Shot 2021-06-04 at 12 37 44 PM" src="https://user-images.githubusercontent.com/814813/120842010-cc80e200-c531-11eb-9c7d-f8be37090103.png">

## 🕵️‍♀️ Extra Details

JPL SPL will block access to LabCAS unless this is fixed!  🚨

**Comment by yuliujpl** [comment]
Resolved
