### ISSUE TITLE
Cache issue with heather's labcas after separating javascript files

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#136]
Heather sent a screenshot in email 4/12/22 with labcas search not working. The javascript console indicates the functions recently separated into a specialized search script is not found. This indicates cache issue even though it shouldn't happen based on previous efforts to set versions for javascript files.

**Comment by hoodriverheather** [comment]
@yuliujpl is this resolved or should we push to 3.1? Just trying to clean up all issues for 3.0.

**Comment by yuliujpl** [comment]
Resolved
