### ISSUE TITLE
add additional hierarchy elements

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#137]
# get patient, study, and series information
                patientID = clean_text(ds.get("PatientID", "NA"))
                studyDate = clean_text(ds.get("StudyDate", "NA"))
                studyDescription = clean_text(ds.get("StudyDescription", "NA"))
                seriesDescription = clean_text(ds.get("SeriesDescription", "NA"))
                # generate new, standardized file name
                modality = ds.get("Modality","NA")
                studyInstanceUID = ds.get("StudyInstanceUID","NA")
                seriesInstanceUID = ds.get("SeriesInstanceUID","NA")
                instanceNumber = str(ds.get("InstanceNumber","0"))

**Comment by hoodriverheather** [comment]
@yuliujpl is this resolved or should we push to 3.1?

**Comment by yuliujpl** [comment]
Done! These are custom categories you can select to generate your hierarchy
