### ISSUE TITLE
test lung semantic reader

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#144]

**Comment by hoodriverheather** [comment]
@yuliujpl I see the annotation drop down at the top of the window for each of the 3 DICOM windows. I think that's OK. All the functionality that the readers need seems to be working.
Did we used to have a way to resize each of the 3 windows individually? I can't seem to remember how to do that. Maybe that's not needed anymore?

**Comment by yuliujpl** [comment]
Yup, that's been developed! Resize is available on the bottom corner of each window!
