### ISSUE TITLE
Data Dashboard - # of files by PI

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#146]
## 🐛 Describe the Bug

@yuliujpl The # of files by PI graph isn't showing on the Data Dashboard. Maybe we should replace with one of the newer graphs from the login page?
I think we should remove the # of PI header for now.

**Comment by yuliujpl** [comment]
@hoodriverheather  removed in edrn-labcas! Happy to replace with another. Do you have any specific ones that you think is more useful?
https://edrn-labcas.jpl.nasa.gov/labcas-ui/a/index.html

**Comment by hoodriverheather** [comment]
@yuliujpl I don't have one right now. It looks great!
