### ISSUE TITLE
Add Uploading data documentation, CDEs and templates to MCL LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#147]
Create the following Help pages for MCL LabCAS:

MCL Data Submission Preparation - https://mcl.nci.nih.gov/resources/informatics_tools/data-upload
See attached file with annotations. Basically, keep items 1 and 3, but rename. You can change these to bullets if you want or keep them numbered (whatever is easiest).
1. MCL CDE Dictionaries, models and templates
3. MCL IDs and Conventions

- Site IDs and Investigator IDs
- MCL Anchor/index date rules
- MCL Participant and Biospecimen identifier rules
- MCL file naming conventions

Sample data and metadata would be it's own bullet or number.
Keep all the links going to the same documents or pages as is on MCL portal.
Keep the Please contact message and keep the diagram.
Delete everything after the diagram.

![Image](https://user-images.githubusercontent.com/58526347/175426263-6c90f650-5235-460a-b2aa-db6349561519.png)

For the MCL CDE Dictionaries, models and templates page - https://mcl.nci.nih.gov/resources/standards/mcl-cdes
See attached screenshot. 
Please add the red text to the two other documents the links are on this page - under Pathology - https://mcl.nci.nih.gov/resources/informatics_tools/labcas-metadata-models

We can keep the upload documentation we have already.
We can keep the download documentation we have already. One weird thing - I don't see any of those images.

Let me know if you want to have a quick call to walk through. Thanks!

**Comment by yuliujpl** [comment]
@hoodriverheather  I'm not sure I following this section!
Please add the red text to the two other documents the links are on this page - under Pathology - https://mcl.nci.nih.gov/resources/informatics_tools/labcas-metadata-models

I see the following links under Pathology in the link you provided:
Pathology
[UC Davis-Borowsky Aperio Metadata Model](https://mcl.nci.nih.gov/resources/informatics_tools/labcasmetadata_aperio_ucdavis-extensions.xlsx)
[MD Anderson-Maitra Pathology Metadata Model](https://mcl.nci.nih.gov/resources/informatics_tools/labcasmetadata_pathology_ipmn_mdanderson-1.xlsx)

Where am I supposed to add these links?

Thanks!

**Comment by hoodriverheather** [comment]
@yuliujpl Please release updated help documentation to prod version of MCL LabCAS.

**Comment by yuliujpl** [comment]
done
