### ISSUE TITLE
JPL LabCAS 2.0 link (top left side menu) should take user back to home page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#15]
The JPL LabCAS 2.0 top link on the blue left side menu should take user back to home page.

**Comment by yuliujpl** [comment]
Done, need to test in container

**Comment by hoodriverheather** [comment]
Change text to say Home
Should take user back to list of collections - https://labcas-dev.jpl.nasa.gov/labcas-ui/application/labcas_collection_table.html

**Comment by hoodriverheather** [comment]
Hi David,
Would you change the text on the left blue menu bar top link "JPL LabCAS 2.0" - change to "Home" and have link take user back to list of collections - https://labcas-dev.jpl.nasa.gov/labcas-ui/application/labcas_collection_table.html
