### ISSUE TITLE
Section 508 Compliance

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#155]
## 🤔 Tell Us About the Feature

JPL has completed accessibility scans of https://edrn-labcas.jpl.nasa.gov/ and found two Section 508 issues that need to be addressed:

1. Every page needs a `<title>`
2. Every image needs a helpful `alt` attribute.

## 🎇 What Solution You'd Like

1. Ensure there's a `<title>` in the `<head>` element
2. Ensure images have `alt` tags, such as `<img id='loading' alt='Please wait while this is loading'…`

## 〽️ Alternative Ideas

1. No way around this; we must have `<title>` elements in the `<head>` element.
2. Feel free to come up with appropriate `alt` descriptions.

## 🗺 Context

[Section 508 detials](https://www.section508.gov). This'll apply to mcl-labcas too.

**Comment by yuliujpl** [comment]
Done!
