### ISSUE TITLE
Analytics for edrn-labcas

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#159]
## 🤔 Tell Us About the Feature

We'd like to collect data on our audience for edrn-labcas.

## 🎇 What Solution You'd Like

Please install the Google Analytics 4™ tag below right after the `<head>` element on every page generated by https://edrn-labcas.jpl.nasa.gov/:

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LQ79946QV2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LQ79946QV2');
</script>
```

**Comment by yuliujpl** [comment]
Done!
