### ISSUE TITLE
Branding for MCL on EDRN-LabCAS

### ISSUE THREAD

**Issue by askarlupka** [EDRN/labcas-ui#160]
## 🐛 Describe the Bug

There is branding and links to MCL-LabCAS on the EDRN-LabCas. 

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Go to https://edrn-labcas.jpl.nasa.gov/labcas-ui/p/index.html
2. Scroll down to the bottom of the page
3. See the error above the copyright, and to the left of the 'Help'

I've just noticed it, so I don't know how long it's been like this. 

## 🔎 Expected Behavior

I don't know if it should reference the MCL if they are not linked to EDRN, especially on every EDRN page. 

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/54122306/203110365-2d34792d-d9e9-41be-b1e4-b4703cfabd25.png)

## 🕵️‍♀️ Extra Details

If you think it'll help, you can add any of the following:
-   Platform
    -   Desktop browser (Firefox 105.0.2)

**Comment by askarlupka** [comment]
Could also think about including more branding for the EDRN such as their logo to differentiate. Currently at first glance it looks more like a JPL-specific data base instead of an EDRN database. I think this is mostly due to the JPL logo being clearly displayed but nothing showcasing EDRN

**Comment by yuliujpl** [comment]
Thanks so much for catching this. Changed to Early Detection Research Network. Will think about adding EDRN logo as well!
