### ISSUE TITLE
Errors trying to open SVS files in MCL LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#164]
## 🐛 Describe the Bug

Get errors and cannot open image for the H&E images in LabCAS. 

## 📜 How To Reproduce

When i'm logged in and go to https://mcl-labcas.jpl.nasa.gov/labcas-ui/z/index.html?fileid=PCA_Pilot_Data/H_and_E_Images/UVM/MCL_PCA_UVM_H%5C%26E_Sp10_slide1_5X.SCN
See screenshot.
<img width="1505" alt="Screen Shot 2022-12-15 at 2 29 27 PM" src="https://user-images.githubusercontent.com/58526347/207982025-623e71e7-48ee-4682-b8b0-adef4460a59f.png">

**Comment by yuliujpl** [comment]
Link works now, resolved!
