### ISSUE TITLE
Links in LabCAS to Protocols broken

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#166]
@yuliujpl some of the links in the Portal have changed due to the portal revamp. Can you update the LabCAS
RDF subject URI? I think that's what you use to link Protocol to the Portal?

For example:
In LabCAS - https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Lung_Team_Project_2
click on the protocol link - https://edrn.nci.nih.gov/protocols/354-validation-of-molecular-biomarkers-for-the/
you get not found because that Protocol is now: https://edrn.nci.nih.gov/data-and-resources/protocols/354-validation-of-molecular-biomarkers-for-the-early-detection-of-lung-cancer-in-the-setting-of-indeterminate-pulmonary-nodules-lung-team-project-2/

**Comment by hoodriverheather** [comment]
@nutjob4life may have a better way to do this IDK?

**Comment by nutjob4life** [comment]
Use the data dispatcher!

     https://edrn.nci.nih.gov/@@dataDispatch?subjectURI=http://edrn.nci.nih.gov/data/protocols/354

**Comment by hoodriverheather** [comment]
@yuliujpl @nutjob4life Hi guys, these links are still broken. I think we should fix asap :)
Thanks! Heather

**Comment by nutjob4life** [comment]
Hi @yuliujpl if you change protocol URLs to this form:
```
https://edrn.nci.nih.gov/@@dataDispatch?subjectURI=http://edrn.nci.nih.gov/data/protocols/NUMBER
```
where `NUMBER` is the protocol number, you won't have to worry where the actual HTML page lives. That "dataDispatch" API will give the browser the correct `Location` as a 301 redirect.
