### ISSUE TITLE
Add MCL Consortium Name to MCL-LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#176]
Add "Molecular and Cellular Characterizations of Screen Detected Lesions (MCL) Consortium" to the login page - https://mcl-labcas.jpl.nasa.gov/labcas-ui/index.html

and to the header once you're in LabCAS.

**Comment by yuliujpl** [comment]
Done! I added MCL to the header within labcas because there isn't enough space for the whole name!

**Comment by hoodriverheather** [comment]
Perfect! thanks!
