### ISSUE TITLE
Not logged in and click on public collection - go to search page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#177]
## 🤔 Tell Us About the Feature

Currently if you're not logged into LabCAS and you click on the Public Collections icon, you're taken to the collections page. This only shows the Vanderbilt public collection. It doesn't show any of the public datasets or files. 

## 🎇 What Solution You'd Like

When a user clicks on Public Collections take them to the search page, so they can see all available public data.

<img width="1172" alt="Screenshot 2023-07-25 at 9 59 05 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/fa050cc9-1ee0-4f08-be63-f2d2715f0c94">

**Comment by yuliujpl** [comment]
@hoodriverheather  do you only want this for mcl-labcas, not edrn-labcas?

**Comment by yuliujpl** [comment]
Done for MCL!

**Comment by hoodriverheather** [comment]
@yuliujpl Good question. We should also do this for EDRN. I noticed it on MCL b/c some of the public data is a dataset, so it wasn't showing in the collections list if you weren't logged in.

**Comment by yuliujpl** [comment]
Done!

**Comment by hoodriverheather** [comment]
@yuliujpl Sweet! Thanks!
