### ISSUE TITLE
Remove ParticipantID and SpecimenID from EDRN LabCAS files list

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#178]
## 🤔 Tell Us About the Feature
Remove ParticipantID and SpecimenID from EDRN LabCAS files list. EDRN doesn't have these metadata fields, so they will always be blank, please remove from the files list.
<img width="1425" alt="Screenshot 2023-09-15 at 12 53 27 PM" src="https://github.com/EDRN/labcas-ui/assets/58526347/8d7af1dd-a45c-4cf3-9733-29c0964a583c">

**Comment by yuliujpl** [comment]
@hoodriverheather done!

**Comment by hoodriverheather** [comment]
@yuliujpl thanks!
