### ISSUE TITLE
Download click agreement and DICOM viewer issues

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#183]
@yuliujpl Dan and I were checking out some of the public DICOM images and ran into a few issues.

Here's the collection/file we were testing -
[https://edrn-labcas.jpl.nasa.gov/labcas-ui/f/index.html?file_id=Automated_Quantitative_Measures_of_Breast_Density_Data/C0250/PROC/C0250_MG_PRO_LCC.dcm#](https://edrn-labcas.jpl.nasa.gov/labcas-ui/f/index.html?file_id=Automated_Quantitative_Measures_of_Breast_Density_Data/C0250/PROC/C0250_MG_PRO_LCC.dcm)

- The click-thru agreement for download isn't popping up when not logged in, even in an incognito window.

- The DICOM viewer doesn't work for Dan in Safari, Chrome or Chrome incognito window (see attached screenshots)
[Screenshot 2023-12-07 at 10.14.23 AM[75]-Dan.pdf](https://github.com/EDRN/labcas-ui/files/13604126/Screenshot.2023-12-07.at.10.14.23.AM.75.-Dan.pdf)

- One thing that was strange was in my browser the breadcrumb path shows a different collection name, but Dan's browser/breadcrumbs doesn't show the same path.
[Screenshot 2023-12-07 at 10.15.31- AM[40]-Dan.pdf](https://github.com/EDRN/labcas-ui/files/13604129/Screenshot.2023-12-07.at.10.15.31-.AM.40.-Dan.pdf)
<img width="1419" alt="Screenshot 2023-12-07 at 10 09 21 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/b77e7084-a790-4c86-ab2e-7440b89e8d9c">

- The DICOM viewer doesn't work for me in Chrome, but does work in Incognito

**Comment by yuliujpl** [comment]
@hoodriverheather dicom should work now whether incognito or not, logged in or out. Breadcrumb should work properly now. These features were well tested when accessed from dataset level, but from file level is when things are breaking, same for the user agreement. I'll get the user agreement fixed soon!

**Comment by hoodriverheather** [comment]
@yuliujpl Thanks for fixing the viewer. It's working for me.

There's a strange thing going on. When I go into an image file metadata and then click the view image icon at the top of the screen, the breadcrumbs change and take me into a different data collection.

Here's an example. Goto - https://edrn-labcas.jpl.nasa.gov/labcas-ui/f/index.html?file_id=Automated_Quantitative_Measures_of_Breast_Density_Data/C0252/PROC/C0252_MG_PRO_LML_2.dcm

Click on the View Image

checkout the breadcrumbs that appear on the top of the image viewer. Then if I click that eventid link, i'm taken to the other collection, but the breadcrumbs make me think i'm in the original collection.

Here are sc
<img width="1390" alt="Screenshot 2023-12-12 at 10 49 38 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/78a3b4da-35f4-4d71-8931-202c6a43dcc1">
reenshots:
<img width="1344" alt="Screenshot 2023-12-12 at 10 49 49 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/594eeffd-06f1-4dc6-b905-6153bdc129c4">
<img width="1420" alt="Screenshot 2023-12-12 at 10 50 12 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/03b0321f-e9a5-4861-a16b-558b8527bb39">

**Comment by yuliujpl** [comment]
breadcrumbs should be fixed

**Comment by yuliujpl** [comment]
Hi Heather,

Both breadcrumbs and file level acceptance agreement should be fixed and enabled now! Please let me know!

Best,
David
________________________________
From: hoodriverheather ***@***.***>
Sent: Tuesday, December 12, 2023 10:52 AM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Download click agreement and DICOM viewer issues (Issue #183)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!LZOvoRamllmlLPgRdqDZ6ydHQ-5ibNDgt0kCz1u1Kp9kFAj5waSD6VUQeXP5eLl_NIe4cff52Xq_K3klnSqVLAseROIWsg$> Thanks for fixing the viewer. It's working for me.

There's a strange thing going on. When I go into an image file metadata and then click the view image icon at the top of the screen, the breadcrumbs change and take me into a different data collection.

Here's an example. Goto - https://edrn-labcas.jpl.nasa.gov/labcas-ui/f/index.html?file_id=Automated_Quantitative_Measures_of_Breast_Density_Data/C0252/PROC/C0252_MG_PRO_LML_2.dcm

Click on the View Image

checkout the breadcrumbs that appear on the top of the image viewer. Then if I click that eventid link, i'm taken to the other collection, but the breadcrumbs make me think i'm in the original collection.

Here are sc
Screenshot.2023-12-12.at.10.49.38.AM.png (view on web)<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/assets/58526347/78a3b4da-35f4-4d71-8931-202c6a43dcc1__;!!PvBDto6Hs4WbVuu7!LZOvoRamllmlLPgRdqDZ6ydHQ-5ibNDgt0kCz1u1Kp9kFAj5waSD6VUQeXP5eLl_NIe4cff52Xq_K3klnSqVLAsBvqwcAA$>
reenshots:
Screenshot.2023-12-12.at.10.49.49.AM.png (view on web)<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/assets/58526347/594eeffd-06f1-4dc6-b905-6153bdc129c4__;!!PvBDto6Hs4WbVuu7!LZOvoRamllmlLPgRdqDZ6ydHQ-5ibNDgt0kCz1u1Kp9kFAj5waSD6VUQeXP5eLl_NIe4cff52Xq_K3klnSqVLAseSWJMCg$>
Screenshot.2023-12-12.at.10.50.12.AM.png (view on web)<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/assets/58526347/03b0321f-e9a5-4861-a16b-558b8527bb39__;!!PvBDto6Hs4WbVuu7!LZOvoRamllmlLPgRdqDZ6ydHQ-5ibNDgt0kCz1u1Kp9kFAj5waSD6VUQeXP5eLl_NIe4cff52Xq_K3klnSqVLAsWVbusww$>

**Comment by hoodriverheather** [comment]
@yuliujpl Looks great! Thanks :)
