### ISSUE TITLE
PubMed Clickable URL

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#184]
@yuliujpl Is it possible make the Pub Med ID in LabCAS a clickable field if there's a URL, so that the users is taken directly to PubMed. There are several collections that have a Pub Med ID.
https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Autoantibody_Biomarkers

See screenshot:
<img width="1152" alt="Screenshot 2024-01-30 at 11 26 40 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/2373deb6-b7ab-4ffe-bbd3-5daeaa09e9f1">

**Comment by hoodriverheather** [comment]
@yuliujpl and @nutjob4life I just added and fixed some a lot of PubMedIDs in the .cfg files in GitHub based on this spreadsheet 
[EDRN LabCAS Data 2024 - NCI-20242603.xlsx](https://github.com/EDRN/labcas-ui/files/14829747/EDRN.LabCAS.Data.2024.-.NCI-20242603.xlsx)

Once we are able to run an ingest on we can get the correct links and make sure they are all clickable in LabCAS. Thanks!

**Comment by yuliujpl** [comment]
Done! Now it is linked!
________________________________
From: hoodriverheather ***@***.***>
Sent: Monday, April 1, 2024 5:14 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] PubMed Clickable URL (Issue #184)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!PEsatqdb2Sclgsj82vz8hAFilhdHj3BC04vVaUAutImD0C4vVduoru9it4OItNetRw1GNovezysbSBhH1T_j3SxRYRX2bA$> and @nutjob4life<https://urldefense.us/v3/__https://github.com/nutjob4life__;!!PvBDto6Hs4WbVuu7!PEsatqdb2Sclgsj82vz8hAFilhdHj3BC04vVaUAutImD0C4vVduoru9it4OItNetRw1GNovezysbSBhH1T_j3SzRLVQvwA$> I just added and fixed some a lot of PubMedIDs in the .cfg files in GitHub based on this spreadsheet
EDRN LabCAS Data 2024 - NCI-20242603.xlsx<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/files/14829747/EDRN.LabCAS.Data.2024.-.NCI-20242603.xlsx__;!!PvBDto6Hs4WbVuu7!PEsatqdb2Sclgsj82vz8hAFilhdHj3BC04vVaUAutImD0C4vVduoru9it4OItNetRw1GNovezysbSBhH1T_j3SwP2hbnJA$>

Once we are able to run an ingest on we can get the correct links and make sure they are all clickable in LabCAS. Thanks!

**Comment by nutjob4life** [comment]
Thanks @yuliujpl. Is there a commit that goes with this fix?
