### ISSUE TITLE
Change password and register links on MCL LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#185]
@yuliujpl Please update the login link to -> email to ic-data ic-data@jpl.nasa.gov. 
Remove "Want to join" section.

https://mcl-labcas.jpl.nasa.gov/labcas-ui/
<img width="1238" alt="Screenshot 2024-02-21 at 2 50 54 PM" src="https://github.com/EDRN/labcas-ui/assets/58526347/63d40a0b-2815-4e46-8e8e-2c6bacdadf0b">

**Comment by yuliujpl** [comment]
Done!

**Comment by hoodriverheather** [comment]
@yuliujpl Can you also change the wording and the link for the forgot password to email us at ic-data@jpl.nasa.gov? There is no longer an MCL Portal. 
Thanks!

**Comment by yuliujpl** [comment]
Done!
________________________________
From: hoodriverheather ***@***.***>
Sent: Tuesday, March 5, 2024 1:50 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Change password and register links on MCL LabCAS (Issue #185)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!IkqbM519HmSjYFRSPdUxmUw-tluy2Ryabv0NSy8p-5IENwqQZ_vgtoKxpLyl14AoTw6dIQ662q1DNcC4lLRaLk7fMGkHww$> Can you also change the wording and the link for the forgot password to email us at ***@***.******@***.***>? There is no longer an MCL Portal.
Thanks!
