### ISSUE TITLE
Error when using breadcrumbs to navigate back from DICOM image viewer

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#187]
## 🐛 Describe the Bug

Get an error/strange results on screen when using breadcrumbs to navigate back to list of "dataset". See screenshots.

<img width="1485" alt="Screenshot 2024-03-22 at 11 10 45 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/61cbff40-0102-4a7f-83c3-2d3a60c5f412">
<img width="1503" alt="Screenshot 2024-03-22 at 11 02 11 AM" src="https://github.com/EDRN/labcas-ui/assets/58526347/f9d14f46-bc7b-4b0d-964b-f03dee489ab1">

https://edrn-labcas.jpl.nasa.gov/labcas-ui/i/index.html?version=3.0.0

**Comment by yuliujpl** [comment]
I believe this may have been resolved in my more recent breadcrumb update!
