### ISSUE TITLE
Add GSA DAP analytics

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#189]
## 🤔 Tell Us About the Feature

The [General Services Administration](https://www.gsa.gov/) has implemented a [Digital Analytics Program or DAP](https://digital.gov/guides/dap/) and requires all public-facing websites to participate—or **they will be shut down**.

This includes the LabCAS for Consortium for Molecular and Cellular Characterization of Screen-Detected Lesions and for the Early Detection Research Network.

## 🎇 What Solution You'd Like

The following `<script>` code needs to appear just before the closing `</head>` tag in each sites' HTML:

- [ ] Add this code for `mcl-labcas`:

```html
<script async type="text/javascript" id="_fed_an_ua_tag"
    src='https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=JPL-mcl-labcas'></script>
```

- [ ] Add this code for `edrn-labcas`:

```html
<script async type="text/javascript" id="_fed_an_ua_tag"
    src='https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=JPL-edrn-labcas'></script>
```

Note that the `&` may or may not need to be escaped as `&amp;` depending on your platform.

## 🩺 Testing

You can confirm the code is properly installed on each site by running, for `mcl-labcas`:

    curl --location --silent 'https://mcl-labcas.jpl.nasa.gov/labcas-ui/templates.html?version=3.0.0#head_template' | egrep digitalgov

and for `edrn-labcas`:

    curl --location --silent 'https://edrn-labcas.jpl.nasa.gov/labcas-ui/templates.html?version=3.0.0#head_template' | egrep digitalgov

If you get _no output_, the code is not correctly installed.

## 📧 Followup

Once this has been implemented and tested successfully, please inform the following people by email of its completion:

- [ ] Lindsey Tran
- [ ] Alicia Cermak
- [ ] Anthony Greicius
- [ ] Randal Jackson
- [ ] Naomi Hartono

**Comment by yuliujpl** [comment]
Done!

**Comment by nutjob4life** [comment]
@yuliujpl thank you kindly. Were there any commits to go with this?
