### ISSUE TITLE
Add Google Analytics to LabCAS UI for Consortium for Molecular and Cellular Characterization of Screen-Detected Lesions 

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#190]
## 🤔 Tell Us About the Feature

Please install the new Google Analytics 4 tag into `mcl-labcas`.

## 🎇 What Solution You'd Like

Put the following `<script>` code into the `<head>` element:

```html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-NNCQXLSQB0"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-NNCQXLSQB0');
</script>
```

## 🩺 Testing

You can confirm the tag is properly installed by running the following:

    curl --location --silent https://mcl-labcas.jpl.nasa.gov/ | egrep googletag

If you get _no output_, the tag is not properly installed.

**Comment by yuliujpl** [comment]
Works like this:
curl --location --silent https://mcl-labcas.jpl.nasa.gov/labcas-ui/index.html | egrep googletag

Since https://mcl-labcas.jpl.nasa.gov/ would redirect to https://mcl-labcas.jpl.nasa.gov/labcas-ui/!
