### ISSUE TITLE
Incognito mode must not be required

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#191]
## 🐛 Describe the Bug

Currently, using labcas-ui almost always requires using the private browsing feature of the web browser, frequently known as "incognito mode". @dcrichto1 considers this a blocking issue. In email with message-ID `<BLAPR09MB69936A3B80E2CBCB060E216D883C2@BLAPR09MB6993.namprd09.prod.outlook.com>` on 2024-04-04, he wrote:

> Sorry…I don’t see this is an issue of being “not optimal” ☺️.  If we have to use incognito or tell our users to use incognito, it’s a blocker bug that we need to raise the priority on!   I’ve spent the last two months on the phone with NCI leadership who are now looking at LabCAS.  We don’t want them running into any issues around usability!

## 📜 How To Reproduce

1. Visit https://edrn-labcas.jpl.nasa.gov/ 
2. Eventually something will require incognito mode

## 🔎 Expected Behavior

Incognito mode shouldn't required.

**Comment by yuliujpl** [comment]
This has been done by removing the "redirect to last visited" feature. This bug only appears when someone tries to enter a nonexistent page, resulting in the UI creating a non-programmatically unresolvable cookie that always try to redirect back to the erroneous page!

**Comment by nutjob4life** [comment]
@yuliujpl thanks for fixing this so quickly! Also: was there a commit that goes with this fix?

(Hint: if you put `Resolves #191` in the commit message, GitHub will record it automatically here.)
