### ISSUE TITLE
Add event ID to the virtual hierarchy drop down

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#192]
## 🤔 Tell Us About the Feature

@hoodriverheather would like "eventID" added to the virtual hierarchy drop down.

## 🗺 Context

See [this comment on the DICOM file structure "clean up" issue](https://github.com/EDRN/EDRN-metadata/issues/83#issuecomment-1406802186).

**Comment by hoodriverheather** [comment]
@yuliujpl Confirmed that this is done. Closing this issue.
