### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#198]
## 🤔 Tell Us About the Feature

Install `robots.txt` files at the root of each LabCAS UI.

## 🎇 What Solution You'd Like

The `robots.txt` should have the following contents:
```
User-agent: *
Disallow: /
```

It needs to be available at the following locations:

- `https://labcas.jpl.nasa.gov/robots.txt`
- `https://edrn-labcas.jpl.nasa.gov/robots.txt`
- `https://mcl-labcas.jpl.nasa.gov/robots.txt`

No subdirectory or subpaths may appear. This may require sysadmin assistance.

**Comment by yuliujpl** [comment]
Requested the SAs:
DSIO-5704

**Comment by nutjob4life** [comment]
@yuliujpl thanks for shepherding this along! 🏎️

**Comment by yuliujpl** [comment]
Done by SAs, verified the urls, done!

**Comment by nutjob4life** [comment]
![the-office](https://github.com/EDRN/labcas-ui/assets/814813/90e6a315-92df-42ab-933f-e5def86ab8fe)
