### ISSUE TITLE
Change the "File box"

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#20]
- Change the "File Box" that displays in the header for the collection details, dataset details. Delete from the file details page.
- Remove the update stat at the bottom of the box. For example, "Last day".

**Comment by yuliujpl** [comment]
Heather, can you kindly clarify what needs to be changed in the file box in the collection and dataset details page?

**Comment by hoodriverheather** [comment]
Hi David, the change is only to remove the bottom update stat. For example, "In the last hour".

One additional item I noticed is that the icons change in the top boxes as you click down in the hierarchy. I think they should remain consistent. For example, the collection icon should always stay the same as it is on the collection level, dataset level, etc.. The dataset icon should always stay the same red icon and the file icon should always stay the same as the green icon.
