### ISSUE TITLE
vunerability

### ISSUE THREAD

**Issue by yuliujpl** [EDRN/labcas-ui#203]
Reflected XSS vulnerability in edrn-labcas, namely if you try this URL:

      https://edrn-labcas.jpl.nasa.gov/labcas-ui/f/index.html?file _id=</a><imgsrc=x onerror=alert(1)>

You'll get a JavaScript alert with "1" in it. 

Not reproducible but will still sanitize the "file_id" parameter of anything unexpected anyway.

**Comment by nutjob4life** [comment]
@yuliujpl thanks for filing this. Once this is resolved, please follow up by email to

- Pedro Ruiz
- Rojeh Yaghoobi
- Mary Rivera

and reference "VDP_639", telling them the vulnerability has been closed 👍

**Comment by yuliujpl** [comment]
@hoodriverheather @nutjob4life issue has been resolved in https://edrn-labcas.jpl.nasa.gov/. Committed to edrn branch for labcas-ui repo (had to commit a new complete branch since the history has a large WebViewer.zip that was past the size constraint for github and needed lfz to remove it from git history).

In terms of the sanitization, I could only remove symbols ', ", >, and <. The reason is these files name has all the symbols in them like (, ), #, &, so those had to be urlencoded.

Thanks!
David

**Comment by nutjob4life** [comment]
@yuliujpl superb! Thanks for looking at this.

Let's see what the [people mentioned in this comment think](https://github.com/EDRN/labcas-ui/issues/203#issuecomment-2136170116) and if they agree, go ahead and close this issue.

**Comment by yuliujpl** [comment]
Closed!

**Comment by nutjob4life** [comment]
NIIIIIICEE!! 🎉
