### ISSUE TITLE
Plain text password in cookies

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#206]
## 👮 Describe the Vulnerability

The image below shows us attempting to log into https://edrn-labcas.jpl.nasa.gov/labcas-ui/index.html?version=3.0.0 and the tool showing the request that contains the plaintext user and password. The only steps taken were:

1. Navigating to https://edrn-labcas.jpl.nasa.gov/labcas-ui/index.html?version=3.0.0
2. Entering test credentials
3. Upon pressing the Login button, the request will be sent and shown

<img width="2560" alt="Screenshot 2024-06-04 at 11 23 42 AM" src="https://github.com/EDRN/labcas-ui/assets/814813/07e2b08e-1d80-4813-b4da-d07579e6a0ff">

**Comment by nutjob4life** [comment]
@yuliujpl when this is fixed, please let the following know:

- Rojeh Yaghoobi
- Susan Neely
- Mary Rivera
- Robert Solorio

**Comment by yuliujpl** [comment]
@nutjob4life @hoodriverheather  issue resolved in edrn-labcas. Ran a few selenium tests and they worked fine! Hopefully the security tests will return success!

**Comment by nutjob4life** [comment]
@yuliujpl excelsior! 🎉 

Once the [folks mention in this comment](https://github.com/EDRN/labcas-ui/issues/206#issuecomment-2147943432) concur, we can close this issue. What a relief! 😌

**Comment by yuliujpl** [comment]
Closing!

**Comment by nutjob4life** [comment]
@yuliujpl let's celebrate! Thanks!
