### ISSUE TITLE
If user not logged in and click on download link provide message

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#209]
@yuliujpl if user is not logged in to LabCAS and they click on the download icon. Please provide the following message: 

Access Denied

You do not have permission to download data. Please apply for an account to get access and see additional data.

**Comment by hoodriverheather** [comment]
@yuliujpl Can you please work on this as soon as possible? I'm hoping once this is done we will be able to release and start to use the User registration process for all public data. We can discuss on our call today.

**Comment by yuliujpl** [comment]
@hoodriverheather can you kindly test? https://labcas-dev.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=VUMC_Lung_Adenocarcinoma_CyTOF_data

**Comment by hoodriverheather** [comment]
@yuliujpl Perfect! Thanks!
