### ISSUE TITLE
Favorite "Box" in header

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#21]
In the header for the collection details and the dataset details:
- Change the heart to a star icon (in all places - header box, side menu, etc.)
- Remove the update stat at the bottom of the box. For example, "Update now"

In the header for the file details:
- remove this box

**Comment by yuliujpl** [comment]
done, need to test in container

**Comment by hoodriverheather** [comment]
The favorites page needs all the "header boxes" updated to match look and feel of all other pages.
