### ISSUE TITLE
Update LabCAS Dev Login Screen

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#210]
@yuliujpl Please update the text and add the following links to the login page on Dev:

Apply for an account - https://labcas-dev.jpl.nasa.gov/biokey/edrn/sign-up/
Change your password - https://labcas-dev.jpl.nasa.gov/biokey/edrn/change-password/
Forgot your password - https://labcas-dev.jpl.nasa.gov/biokey/edrn/forgotten/

Also, please extend the white space past the text.

<img width="1460" alt="Screenshot 2024-06-26 at 3 03 59 PM" src="https://github.com/EDRN/labcas-ui/assets/58526347/979279c8-493c-412a-8c35-a1f77867c9a1">

**Comment by yuliujpl** [comment]
Need to flip non-edrn vs edrn header. Need to hyperlink with previous login links into the edrn member section's hyperlinks.

**Comment by hoodriverheather** [comment]
@yuliujpl For the invalid login message box - use the text at bottom of page for the text in the message box EDRN Members with links and Non EDRN Member with links. :)

**Comment by hoodriverheather** [comment]
@yuliujpl There's another message box that needs to be updated. If a user login fails. From login page, enter invalid user credentials. Message should be (same test and links as on login page):
Login falled.
Non-EDRN Members/Research Communitv:
- Apply for an account
• Change your password
- Forgot your password
EDRN Members:
- Apply for an account
- Reset or change your password
If you need additional help, contact the JPL Informatics Center at ic-portal@jpl.nasa.gov
<img width="1477" alt="Screenshot 2024-07-02 at 2 12 20 PM" src="https://github.com/EDRN/labcas-ui/assets/58526347/15d78d2e-545b-46be-99b6-0a3d68b29b73">

**Comment by yuliujpl** [comment]
Done!
________________________________
From: hoodriverheather ***@***.***>
Sent: Tuesday, July 2, 2024 2:42 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] Update LabCAS Dev Login Screen (Issue #210)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!ND-XIIpcvlkfJhcJg_oILOKct7UsEfPUjnYv142SquOjwf85ub7P7XkPI2Z9Q-0cssXk-20kB2-9B5uarAbpqZ0UhDZUtA$> There's another message box that needs to be updated. If a user login fails. From login page, enter invalid user credentials. Message should be (same test and links as on login page):
Login falled.
Non-EDRN Members/Research Communitv:

  *   Apply for an account
• Change your password
  *   Forgot your password
EDRN Members:
  *   Apply for an account
  *   Reset or change your password
If you need additional help, contact the JPL Informatics Center at ***@***.******@***.***>

Screenshot.2024-07-02.at.2.12.20.PM.png (view on web)<https://urldefense.us/v3/__https://github.com/EDRN/labcas-ui/assets/58526347/15d78d2e-545b-46be-99b6-0a3d68b29b73__;!!PvBDto6Hs4WbVuu7!ND-XIIpcvlkfJhcJg_oILOKct7UsEfPUjnYv142SquOjwf85ub7P7XkPI2Z9Q-0cssXk-20kB2-9B5uarAbpqZ0Dr4aVuw$>

**Comment by yuliujpl** [comment]
@hoodriverheather can't change the reset password to go directly to the reset page. The reason is the compass fhrc page automatically redirects to the login page even using the reset url, then it doesn't do it subsequently. So anytime you try to go to that reset url in an incognito window, you'll see that it will redirect to the login page!

**Comment by hoodriverheather** [comment]
@yuliujpl Perfect. Thanks!
