### ISSUE TITLE
EDRN LabCAS: logging in a second time in LabCAS fails

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#211]
## 🐛 Describe the Bug
Login to LabCAS Prod and Dev

See @nutjob4life test results:
https://gist.github.com/nutjob4life/c6dc41641b3e2a5425230b4a224687a9

**Comment by nutjob4life** [comment]
@yuliujpl if it helps, the backend log file is at:

    /usr/local/labcas/backend/home/apache-tomcat/logs/catalina.out

Let me know how I can help

**Comment by yuliujpl** [comment]
@nutjob4life  that is super helpful, it showed the token was breaking it! @hoodriverheather can you try again?

**Comment by hoodriverheather** [comment]
@yuliujpl @nutjob4life This is working now!

**Comment by nutjob4life** [comment]
@hoodriverheather thanks for the good news 🎉
