### ISSUE TITLE
multiple labcas.dicom: tags error out in edrn-labcas.jpl.nasa.gov

### ISSUE THREAD

**Issue by yuliujpl** [EDRN/labcas-ui#214]
multiple labcas.dicom: tags error out in edrn-labcas.jpl.nasa.gov

**Comment by yuliujpl** [comment]
Can I get a +1? @hoodriverheather

**Comment by hoodriverheather** [comment]
@yuliujpl can you remind me what this is fixing. sorry :)

**Comment by yuliujpl** [comment]
Ah sorry, when you try to select multiple of those labcas:dicom virtual hierarchy tags, it will error out/break. You could only select one and all the other tags had to be regularly named tags. It should be fixed now so you can go crazy with the virtual hierarchy tags if you wanted to :)
________________________________
From: hoodriverheather ***@***.***>
Sent: Monday, July 15, 2024 8:22 AM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] multiple labcas.dicom: tags error out in edrn-labcas.jpl.nasa.gov (Issue #214)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!Ki8mtL0JIqwB9VNwz-iNrBMWt6h-WtYFfAc3CGVGU_Gbxgo2qIWUT8kUcXTA2YyklXh9kvYHhJmU9s4133qJufkV9PZt8Q$> can you remind me what this is fixing. sorry :)

**Comment by hoodriverheather** [comment]
@yuliujpl is this deployed on dev or prod? Thanks!

**Comment by yuliujpl** [comment]
Oh right, it was deployed in prd when we looked at it together and I copied it to dev, but obviously we can't look at it in dev because the data isn't there! Sorry for the confusion

________________________________
From: hoodriverheather ***@***.***>
Sent: Monday, July 15, 2024 12:36 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [EDRN/labcas-ui] multiple labcas.dicom: tags error out in edrn-labcas.jpl.nasa.gov (Issue #214)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!NyAS5qX-8K_Rwm5geCYZuMQUgySD3YInN72GMHR7reU2iWIGddpOlP4vH1bzEmzYAcqFmY-2JAXU3arLU8Rmeiw8MhqbkQ$> is this deployed on dev or prod? Thanks!

**Comment by hoodriverheather** [comment]
@yuliujpl looks good to me.
Thanks!
