### ISSUE TITLE
Add an announcement to LabCAS news and announcements icon

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#216]
@yuliujpl Please add this announcement to LabCAS. 
Announcement: Update to EDRN Data Access
We are implementing an important update regarding access to EDRN data holdings:
 
Users can still browse and explore EDRN data holdings that are publicly available without LabCAS credentials.
 
To enhance security and manage data access more effectively, user registration is required to view or download publicly available file metadata and data.
 
How to Access:
EDRN Members:
[Apply](https://www.compass.fhcrc.org/edrns/pub/user/application.aspx?t=app&sub=form1&w=1&p=3&t2=sub&part=signup) for an account
[Reset or change](https://www.compass.fhcrc.org/edrns/pub/user/resetPwd.aspx?t=pwd&sub=form&w=1&p=3) your password
 
Non-EDRN Members: [Apply for a LabCAS account](https://edrn-labcas.jpl.nasa.gov/biokey/edrn/sign-up/) to gain access.
 
We appreciate your understanding and cooperation with this new requirement. If you have any questions or need assistance, please contact our support team.

**Comment by yuliujpl** [comment]
@hoodriverheather, where do I update this? Should I do on dev first?

**Comment by hoodriverheather** [comment]
@yuliujpl Dev first would be great! Thanks!

**Comment by yuliujpl** [comment]
Done!

**Comment by yuliujpl** [comment]
@hoodriverheather pushed to edrn prod!

**Comment by hoodriverheather** [comment]
@yuliujpl Thanks!

**Comment by yuliujpl** [comment]
Closing, considered done!
