### ISSUE TITLE
Add file sizes to LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#220]
From Sean:
If we could get the total size of a collection displayed somewhere on the UI, super.
 
Add to that sizes of datasets within a collection, even better.
 
And some day in the future: on the all collections view, a column showing the total sizes of each collection. As you drill down you can see sizes as you go: dataset sizes; nested dataset sizes; files in a dataset sizes; individual file size. That'd be pretty nifty!
 
Take care,
-SK
 
From: Ashish Mahabal <[aam@astro.caltech.edu](mailto:aam@astro.caltech.edu)>
Sent: Tuesday, July 30, 2024 6:08 PM
To: Kincaid, Heather L (US 398G-Affiliate) <[heather.kincaid@jpl.nasa.gov](mailto:heather.kincaid@jpl.nasa.gov)>; Liu, David (US 3902-Affiliate) <[david.liu@jpl.nasa.gov](mailto:david.liu@jpl.nasa.gov)>; Kelly, Sean C (US 398G-Affiliate) <[sean.c.kelly@jpl.nasa.gov](mailto:sean.c.kelly@jpl.nasa.gov)>
Subject: Re: dataset sizes
 

Hi David,

If filesize is too granular, at least collection size will be great.
If also dataset size, even better (a subset of collection).

-ashish

On 7/30/24 3:58 PM, Kincaid, Heather L (US 398G-Affiliate) wrote:
Hi David,
That would be great.
We also just spoke about seeing if it is easy for you to include the file size, size of a dataset and size of a collection in LabCAS UI? If that’s difficult, we can wait to figure out after workshop. Just let me know.
 
Sean – add anything about that I may have missed.
Thanks,
Heather
 
From: Liu, David (US 3902-Affiliate) [<david.liu@jpl.nasa.gov>](mailto:david.liu@jpl.nasa.gov)
Date: Tuesday, July 30, 2024 at 2:22 PM
To: Kelly, Sean C (US 398G-Affiliate) [<sean.c.kelly@jpl.nasa.gov>](mailto:sean.c.kelly@jpl.nasa.gov), Ashish Mahabal [<aam@astro.caltech.edu>](mailto:aam@astro.caltech.edu), Kincaid, Heather L (US 398G-Affiliate) [<heather.kincaid@jpl.nasa.gov>](mailto:heather.kincaid@jpl.nasa.gov)
Subject: Re: dataset sizes

So should I go ahead and enable collection level download feature @Kincaid, Heather L (US 398G-Affiliate) for edrn-labcas, starting with labcas-dev first?

**Comment by yuliujpl** [comment]
Added at collection level in labcas-dev, but the size seems big, 30gb, 100gb, 1tb somtimes!

Please let me know and I can implement at dataset level,
David
________________________________
From: hoodriverheather ***@***.***>
Sent: Tuesday, August 6, 2024 3:33 PM
To: EDRN/labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] [EDRN/labcas-ui] Add file sizes to LabCAS (Issue #220)


From Sean:
If we could get the total size of a collection displayed somewhere on the UI, super.

Add to that sizes of datasets within a collection, even better.

And some day in the future: on the all collections view, a column showing the total sizes of each collection. As you drill down you can see sizes as you go: dataset sizes; nested dataset sizes; files in a dataset sizes; individual file size. That'd be pretty nifty!

Take care,
-SK

From: Ashish Mahabal ***@***.******@***.***>>
Sent: Tuesday, July 30, 2024 6:08 PM
To: Kincaid, Heather L (US 398G-Affiliate) ***@***.******@***.***>>; Liu, David (US 3902-Affiliate) ***@***.******@***.***>>; Kelly, Sean C (US 398G-Affiliate) ***@***.******@***.***>>
Subject: Re: dataset sizes

Hi David,

If filesize is too granular, at least collection size will be great.
If also dataset size, even better (a subset of collection).

-ashish

On 7/30/24 3:58 PM, Kincaid, Heather L (US 398G-Affiliate) wrote:
Hi David,
That would be great.
We also just spoke about seeing if it is easy for you to include the file size, size of a dataset and size of a collection in LabCAS UI? If that’s difficult, we can wait to figure out after workshop. Just let me know.

Sean – add anything about that I may have missed.
Thanks,
Heather

From: Liu, David (US 3902-Affiliate) ***@***.***> ***@***.******@***.***>
Date: Tuesday, July 30, 2024 at 2:22 PM
To: Kelly, Sean C (US 398G-Affiliate) ***@***.***> ***@***.******@***.***>, Ashish Mahabal ***@***.***> ***@***.******@***.***>, Kincaid, Heather L (US 398G-Affiliate) ***@***.***> ***@***.******@***.***>
Subject: Re: dataset sizes

So should I go ahead and enable collection level download feature @Kincaid<https://urldefense.us/v3/__https://github.com/Kincaid__;!!PvBDto6Hs4WbVuu7!OQLS6wkwT_BM2K8ErskhX_phR5CarA6Se1p5sKWjBcBab4ZGeOk7S16h9LFjIqhtZ9BJznHWJan1FpkwiDRDgopEgngTag$>, Heather L (US 398G-Affiliate) for edrn-labcas, starting with labcas-dev first?

**Comment by hoodriverheather** [comment]
@yuliujpl Please remind me to test after workshop :) We can't include this in prod until after next week :)

**Comment by yuliujpl** [comment]
Please test!

**Comment by hoodriverheather** [comment]
@yuliujpl This is great at the collection level!
Can you also implement the size at the following:

- entire LabCAS - show on the search screen at top
<img width="1519" alt="Screenshot 2024-10-07 at 2 09 01 PM" src="https://github.com/user-attachments/assets/3e371554-b413-4275-b97b-b97173e2a2b1">

- at dataset level
this for sure
<img width="1531" alt="Screenshot 2024-10-07 at 2 10 11 PM" src="https://github.com/user-attachments/assets/3c126167-0a23-4661-bd01-1c7d03acc74b">

this if you think it's easy
<img width="1526" alt="Screenshot 2024-10-07 at 2 18 58 PM" src="https://github.com/user-attachments/assets/b455d0ae-8c3d-4fa0-b941-39702ff5844d">

**Comment by yuliujpl** [comment]
Added all except the last request, since it's calculating at every subdirectory from scratch, it's going to slow down the browser speed! I can add it if you want and we can see if it still performs okay for collections with a lot of datasets like Combined_Imaging_and_Blood_Biomarkers_for_Breast_Cancer_Diagnosis in labcas-dev!

**Comment by hoodriverheather** [comment]
@yuliujpl Sounds good. Let's leave it for now.
