### ISSUE TITLE
Change `Children` to something else

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#221]
## 🤔 Tell Us About the Feature

During a call with Erin Fowler and Dr John Heine (2024-08-09), it was pointed out that "Children Datasets" suggests the data comes from child participants, i.e., people under age 18.

## 🎇 What Solution You'd Like

Instead of "Children" in the UI—which makes sense from a computer science perspective—let's try another word. Some ideas:

- Subsets
- Subdatasets
- Nested datasets

## 〽️ Alternative Ideas

- Branch datasets
- Linked datasets
- Contained datasets
- Comprising datasets

**Comment by hoodriverheather** [comment]
@yuliujpl @nutjob4life I like Nested datasets. Thanks!

**Comment by yuliujpl** [comment]
Changed to Nested!

**Comment by nutjob4life** [comment]
"Nested" I like it! Thanks @yuliujpl!

**Comment by hoodriverheather** [comment]
@yuliujpl Perfect! Thanks!
