### ISSUE TITLE
expose collection level download with 1Gb size constraint

### ISSUE THREAD

**Issue by yuliujpl** [EDRN/labcas-ui#224]
## 🤔 Tell Us About the Feature

Replace this with a clear and concise description of the problem you're tying to solve; for example: I'm frustrated when … or I wish it were easier to …

## 🎇 What Solution You'd Like

Here, put a clear and concise description of what you want to happen.

## 〽️ Alternative Ideas

If you'd like, put in a description of any alternative solutions or features you've considered.

**Comment by yuliujpl** [comment]
Done @hoodriverheather  users an download <3gb collection using the download collection snapshot icon at the top left of a collection. This button will only show up if the total file size is les than 3gb!

**Comment by hoodriverheather** [comment]
@yuliujpl This is great!! +1 to push to Prod. Thanks :)
