### ISSUE TITLE
MCL LabCAS unable to login, except incognito (sometimes)

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#233]
## 🐛 Describe the Bug
@yuliujpl I am unable to login to MCL LabCAS, except sometimes in incognito. I have to close out of chrome incognito window and can the login. It doesn't work at all in my regular Chrome. I had @nutjob4life restart the server, but still not working.

Can I help to debug anything, please let me know. 
thanks,
Heather

**Comment by nutjob4life** [comment]
@hoodriverheather as of 2024-10-16, I can log into MCL LabCAS.

**Comment by hoodriverheather** [comment]
@nutjob4life @yuliujpl I am still unable to login to MCL LabCAS when using regular chrome window. I'm reopening.
    https://mcl-labcas.jpl.nasa.gov/labcas-ui/

**Comment by hoodriverheather** [comment]
@yuliujpl fixed by removing old cookie. 👍
