### ISSUE TITLE
Not logged in to Portal and Click on Data Collection can you be taken to the public view of this?

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-ui#237]
## 🤔 Tell Us About the Feature
@nutjob4life and @yuliujpl Is it possible - 
If a user is in the EDRN Portal and is not logged in and clicks on a Data Collection link, they are taken to the public view of that Data Collection in LabCAS? Currently, users are prompted to log into LabCAS.

**Comment by nutjob4life** [comment]
Moving to labcas-ui; the portal has no control over this, sorry

**Comment by nutjob4life** [comment]
@hoodriverheather curiously, I tried it just now, and it worked correctly.

1. I started on [this page on the portal](https://edrn.nci.nih.gov/data-and-resources/data/autoantibody-biomarkers/) (logged in or not)
2. I clicked the blue button "View this Data Collection in LabCAS"
3. It took me [to this page in LabCAS](https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=Autoantibody_Biomarkers), no login prompt

<img width="1123" alt="Screenshot 2024-11-08 at 3 47 41 PM" src="https://github.com/user-attachments/assets/77ef8caf-77fc-471a-93ed-1afda4e46289">

Also worked in private browsing window (Edge) and an incognito window (Chrome)

**Comment by hoodriverheather** [comment]
@nutjob4life maybe didn't work because i was in Dev Portal? I'm trying to test it rn. I will close this issue. thanks.
