### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by hkincaid** [EDRN/labcas-ui#6]
Allow user to search either using a search text box or using a facet search (see attached example).

- User could use a generic search schema or select a specific schema (pathology, genomics, etc. that would have more specific metadata).

- Search would return - Name, Type, Description, Thumbnail, Size

- MouseOver/Click would show additional metadata.

- Would be great to have a "shopping cart" where user could select files for download and place in "cart". Once in cart, allow to add/delete, then download

-

**Comment by yuliujpl** [comment]
The only thing missing is the shopping cart experience, which is quite challenging to solve for now. Will create a new request just for this
