### ISSUE TITLE
Multiple login prompts

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#97]
## 💁‍♀️ Summary

LabCAS UI seems to redundantly ask visitors to log in, even after they've already logged in.

## 📜 Reproduction

To reproduce as of `Fri Aug 14 22:03:26 UTC 2020`, do the following:

1. In the browser, open a new, non-incognito browser window.
2. In this window, visit https://edrn-labcas.jpl.nasa.gov/
3. Log in following the prompts for username and password.
4. You should now be viewing "LABCAS Collections".
5. Open a second new, non-incognito browser window.
6. In this window, visit https://edrn-labcas.jpl.nasa.gov/

At this point, the second window should be showing "LABCAS Collections" because you're already logged in. Instead, it shows the login prompt.

## 🖥 Context

This seems to occur on Chrome 84.0.4147.105, Firefox 79.0, and Safari 13.1.2 (15609.3.5.1.3) on macOS 10.15.6. It also occurs on https://mcl-labcas.jpl.nasa.gov/

## 🖼 Screenshot

In this shot, browser windows (left to right) are Chrome, Firefox, and Safari; top-to-bottom are first window, then second window.
![Screen Shot 2020-08-14 at 5 09 58 PM](https://user-images.githubusercontent.com/814813/90296448-17b9ef00-de51-11ea-95f3-5fb3ea662e3f.png)

**Comment by yuliujpl** [comment]
Fixed
