### ISSUE TITLE
EDRN password recovery URL incorrect

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/labcas-ui#98]
## 💁‍♀️ Summary

On the [EDRN LabCAS instance](https://edrn-labcas.jpl.nasa.gov/), the forgotten password URL is https://www.compass.fhcrc.org/edrns/login.asp?m=Your%20session%20has%20timed%20out.%20Please%20login%20again

It should be https://www.compass.fhcrc.org/edrns/pub/user/resetPwd.aspx?t=pwd&sub=form&w=1&p=3

(The registration URL is correct! ✅)

## 📜 Reproduction

To reproduce as of `Fri Aug 14 22:18:50 UTC 2020`, do the following:

1. In your browser app, open a new, non-incognito browser window.
2. In this window, visit https://edrn-labcas.jpl.nasa.gov/
3. Copy the hyperlink for `we can send you a new one`.

## 🖥 Context

This seems to occur on Chrome 84.0.4147.105, Firefox 79.0, and Safari 13.1.2 (15609.3.5.1.3) on macOS 10.15.6. It also occurs on https://mcl-labcas.jpl.nasa.gov/

## 🖼 Screenshot

![Screen Shot 2020-08-14 at 5 20 00 PM](https://user-images.githubusercontent.com/814813/90296877-6a47db00-de52-11ea-877a-623d06c8cc2f.png)

**Comment by yuliujpl** [comment]
Fixed in labcas-dev, will migrate
